### ISSUE TITLE
Create `win-arm64` launchers

### ISSUE THREAD

**Issue by jaimergp** [conda/conda-launchers#4]
Current scripts only support `win-64`. We rely on MSYS2 compilers for this (`m2w64-toolchain_win-64` in conda-forge). Unfortunately there's no `m2w64-toolchain_win-arm64` yet. We could maybe use the MSVC compilers ([`vs_win-arm64`](https://anaconda.org/conda-forge/vs_win-arm64)), but there's this warning in the build scripts:

https://github.com/conda/conda-launchers/blob/22336e2c23fe5cc3cb8d664c647029c101251ca0/recipe/build.sh#L26-L27

Maybe it's a good temporary workaround?

Also, I'm not sure, but shouldn't Windows be able to emulate the x64 launchers just fine?

**Comment by wolfv** [comment]
Awesome! 
Yes, I am also wondering about the emulation. Could be that it just works. On the other hand, native would be nicer.

We could also try to compile via zig :)

Or maybe newer MSVC versions have gotten better? Who knows.

**Comment by chawyehsu** [comment]
I've just successfully migrated the project to using rattler-build and built the launchers for win-arm64 by leveraging the great Zig build system. The work was done and tested on my Windows ARM laptop. See: https://github.com/chawyehsu/conda-recipes/commit/7d5f33f0512254fa0d25ebdb377768f7a911ef73

The executable size is around 50KB as I can see, and artifacts are available in [the CI run](https://github.com/chawyehsu/conda-recipes/actions/runs/11703616256).

If it sounds good I'm willing to PR send it back to this repo.

There's one question, I wonder if the launchers would be distributed as a `conda-launchers` package, and if it is then should it be noarch and pack all launchers for different architectures.

**Comment by wolfv** [comment]
Awesome work @chawyehsu - I would LOVE to use that in `rattler`.

**Comment by jaimergp** [comment]
Zig to the rescue! Thanks for the initiative! A PR is indeed more than welcome. Please open one but leave the `meta.yaml` in place for backwards compatibility.

Not sure about the noarch question. Maybe yes, maybe not? We can make them noarch:generic but name them like we do with compilers (e.g. with a platform suffix) so folks can co-install several of them, I guess?

**Comment by jaimergp** [comment]
Closed by #7 and #9
